### ISSUE TITLE
Сделал простейший Wordpress-плагин

### ISSUE THREAD

**Issue by beshur** [ilyabirman/Jouele#11]
Привет.

Сделал простейший Wordpress-плагин https://github.com/beshur/wp-jouele.

Он ничего не делает, а просто включает файлы Jouele на всех страницах.

В планах - добавить кнопку в редактор, которой можно будет вставить ссылку с нужным классом.

**Comment by ilyabirman** [comment]
Отлично, спасибо. А почему это issue? Вроде в этом же нет проблемы? :-)
