### ISSUE TITLE
Чтение исполнителя и названия песни из mp3-файла

### ISSUE THREAD

**Issue by hypnocolor** [ilyabirman/Jouele#13]
Было бы клёво добавить опцию, позволяющую вместо текста ссылки принудительно подставлять исполнителя и название песни из ID3-тегов соответствующего файла. Если теги не указаны — оставлять текст, который был у ссылки по умолчанию.

**Comment by Sogl** [comment]
👍

**Comment by eugene-lazarev** [comment]
К сожалению, читать теги mp3-файлов на джаваскрипте очень сложно. Библиотека [jsmediatags](https://github.com/aadsm/jsmediatags) весит более 100 КБ.
Вы можете самостоятельно подключить эту библиотеку (или прочитать теги любым другим образом) и передать полученные данные в Жуэль через `JoueleInstance.setOptions({ title: "" })`.
