### ISSUE TITLE
About the version tag

### ISSUE THREAD

**Issue by x09326** [ilyabirman/Jouele#19]
Hi, I'm going to host this project on [https://cdnjs.com/](url).

Can you update the version 2.1.2 ?
Because I saw there are still something haven't been updated like package.json.

Thank you for your help.

**Comment by eugene-lazarev** [comment]
Hi!

Thanks for your issue.
Please provide more information what we need to do because as I see in the master-branch there is correct package.json with 2.1.2 version.

Thank you.

**Comment by x09326** [comment]
I think the master is no problem.
But the files like ```package.json``` with tag 2.1.2 is still version 2.1.1.

**Comment by eugene-lazarev** [comment]
Hi again!

Please check is everything OK now? I moved the tag to the latest master commit.

**Comment by x09326** [comment]
@eugene-lazarev Thank you. :smile: 
I will start to send a pull request to add this project in cdnjs.
