### ISSUE TITLE
некорректное определение координаты X на телефоне

### ISSUE THREAD

**Issue by zeempt** [ilyabirman/Jouele#28]
Здравствуйте,
Заметил, что на андроиде в браузере google chrome при масштабе, отличном от 100%, некорректно определяется координата нажатия на полосе прокрутки, в других браузерах и ОС не проверял.
Проблема решается с помощью window.pageXOffset, его нужно сложить с (e.pageX-r.offset().left):
(window.pageXOffset+e.pageX-r.offset().left)
Программистом не являюсь, так что в кроссбраузерности, универсальности и правильности решения проблемы не уверен.

**Comment by eugene-lazarev** [comment]
@zeempt, в версии [v3.0.4-free](https://github.com/ilyabirman/Jouele/releases/tag/v3.0.4-free) этой проблемы быть не должно.
