### ISSUE TITLE
Что нового в 3.0.4?

### ISSUE THREAD

**Issue by smartcorestudio** [ilyabirman/Jouele#29]
Нигде не нашел чейджлога о том что же нового в новой версии, стоит ли обновляться до нее. Размер JS-файла заметно увеличился. Появилась ли поддержка других аудиоформатов кроме MP3?

**Comment by eugene-lazarev** [comment]
@smartcorestudio, спасибо за вопрос! Чейнджлог будет готов в ближайшее время. Если кратко, мы полностью переписали Жуэль :–) Теперь он стабильнее, точнее и надёжнее. И ещё полностью поменялся API. Размер файла увеличился менее чем на 10 КБ.
