### ISSUE TITLE
По окончании воспроизведения можно убирать прошедшее время

### ISSUE THREAD

**Issue by maximal** [ilyabirman/Jouele#31]
![image](https://user-images.githubusercontent.com/980679/42156678-5c4d5c34-7df4-11e8-9fac-ac7c721b286d.png)

Когда трек закончил играть, можно и убирать прошедшее время. Всё равно, когда я нажму [Воспроизведение] опять, оно сначала пойдёт.

**Comment by eugene-lazarev** [comment]
Спасибо за идею!
