### ISSUE TITLE
Как изменить скорость воспроизведения?

### ISSUE THREAD

**Issue by vvscode** [ilyabirman/Jouele#41]
Не вижу API для изменения скорости воспроизведения - это предусмотрено? или PR is welcome? =)

**Comment by eugene-lazarev** [comment]
Не было необходимости добавлять эту фичу в проект. Если хотите — велкам :)

**Comment by vvscode** [comment]
Мне на разок =)

Если кому-то пригодиться:

Jouele (3я версия) с большего UI обертка для [howler.js](https://github.com/goldfire/howler.js), у которого есть свойство [rate](https://github.com/goldfire/howler.js#rate-number-10)

Но в моем случае (makeright) на сайте использовался Jouele 2й версии - там не использовался `howler`, но помог следующий сниппет

```js
// $ - глобальный jQuery инстранст
// .Jouele - доступ к объекту плагина
// .lastPlayed - текущий трек
// .$jPlayer[0] - доступ к плееру-обертке (элемет виртуальный, в DOM не встроен, поэтому чрез `querySelector` не находится
// .playbackRate - изменение скорости https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate
$.Jouele.lastPlayed.$jPlayer[0].querySelector('audio').playbackRate = 2;
```
