### ISSUE TITLE
Не подхватывает a.jouele, загруженные через ajax

### ISSUE THREAD

**Issue by smortus** [ilyabirman/Jouele#6]

**Comment by beshur** [comment]
Я [обновил плагин в своём форке](
https://github.com/beshur/jouele), так что теперь его можно вызывать самому после завершения AJAX-запроса типо так:
```
$("a.jouele").Jouele();
// после работы плагина ссылки заменяются div'ом с самим плеером
```

Сделал пулл-реквест https://github.com/ilyabirman/Jouele/pull/10, но пока Илья не подтвердил.

**Comment by eugene-lazarev** [comment]
Please have a look to Jouele 2.0. If something still is uncovered, please let us know.
Thank you.

**Comment by KravtsovAlexandr** [comment]
> Я [обновил плагин в своём форке](https://github.com/beshur/jouele), так что теперь его можно вызывать самому после завершения AJAX-запроса типо так:
> 
> ```
> $("a.jouele").Jouele();
> // после работы плагина ссылки заменяются div'ом с самим плеером
> ```
> 
> Сделал пулл-реквест #10, но пока Илья не подтвердил.

$("a.jouele").jouele(); если быть точнее
