### ISSUE TITLE
Управление громкостью

### ISSUE THREAD

**Issue by AzMandius** [ilyabirman/Jouele#8]
Подумал - вот наконец достойная стильная замена плееру на моем сайте, очень порадовался, собрался забирать, поюзал немного демку на блоге автора, и тут заметил что, к великому разочарованию, нет возможности управлять громкостью звука. Нужно ли это? Вспомните бету 2-версии SoundCloud-а, там разработчики тоже решили что это лишнее, и убрали. Фидбэк был шумно-негативный, вернули.

Спасибо за прекрасный плеер, жаль не возьму.

**Comment by eugene-lazarev** [comment]
@AzMandius, пока мы не планируем добавлять управление громкостью в Жуэль. Однако, ты можешь воспользоваться АПИ Джейплеера. Экземпляр Джейплеера лежит в экземпляре Жуэля: `Jouele.$jPlayer.jPlayer`.
